### PR TITLE
Adds EPICSTel screen (mainly)

### PR DESCRIPTION
**Pull request by gfrn**
Adds EPICSTel screen, aligns buttons on launcher/removes unused imports.

Paramiko was also added as a requirement (used for SSH connections to alter the EPICSTel remote files).

### CODE REVIEW

**Comment by carneirofc** [comment]
Several changes have been made to the master branch, and they will provoke some conflicts.
@ntanck could you sync your fork from master again?

**Comment by carneirofc** [comment]
I've just noticed your PR, feel free to include me as a reviewer or send a message.

**Review by gfrn — COMMENTED** [review]
Synced to upstream

**Comment by gfrn** [comment]
Some changes were made to the launcher to give it a more predictable behavior, however, they can be safely ignored if they don't fit in.

**Comment by carneirofc** [comment]
Cool, I will merge ASAP.

**Comment by carneirofc** [comment]
I've included pandas as a requirement for the project https://github.com/lnls-sirius/pydm-opi/blob/master/requirements.txt#L4

**Pull request merged**
